Spain autonomous communities and provinces
GeoGuess/GeoGuess-Maps pull request #33
Opened 2022-03-16 14:26 UTC by Rukant

I just changed the maps.json file and added the new areas to the corresponding folder. Check if everything is fine specially the nominatim query because I don't know if those are the correct params.

2022-03-16 19:14 UTC, BilelJegham requested changes
Thanks for your contribution;
Please follow the README (https://github.com/GeoGuess/GeoGuess-Maps/blob/main/README.md)

You should edit `src/list.maps.json` or `src/list.areas.json`, not maps.json ;)

2022-03-16 20:30 UTC, Rukant commented
Ok, the maps.json file is back to it's original state and the changes are now in the src/list.areas.json. For the step of the generation of the i18n keys I don't know if I need to do something else.

2022-03-16 22:15 UTC, Rukant commented
Syntax error in the JSON file is fixed.

2022-03-17 22:20 UTC, BilelJegham requested changes
Hi, thx for the fix. 
Tested both GeoJSON, we have smalls issues with labels.

Best regards

2022-03-17 22:20 UTC, BilelJegham commented on public/geojson/areas/spain_autonomous_communities.geojson
> +{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"ISO":"ESP","NAME_0":"Spain","ID_1":935,"NAME_1":"Andalucía","VARNAME_1":"Andalousie|Andaluc¡a|Andalusien|Andaluzia","HASC_1":"
Unfortunately, we have an issue in this geojson, some "provincia" values don't match with OpenStreetMap :

1. Received from openstreetmap "Navarra" but "Comunidad Foral de Navarra"  in geojson
Tested with https://nominatim.openstreetmap.org/reverse?format=json&lat=42.63008462628674&lon=-1.6433664720849774&zoom=5&addressdetails=1&accept-language=es
2. Received from openstreetmap "Asturias" but "Principado de Asturias" in geojson
Tested with https://nominatim.openstreetmap.org/reverse?format=json&lat=43.27224333834266&lon=-5.946760248088729&zoom=5&addressdetails=1&accept-language=es

2022-03-17 22:20 UTC, BilelJegham commented on src/list.areas.json
> +    "spain-provinces": {
Unfortunately, we have an issue in this geojson, some "provincia" values don't match with OpenStreetMap :
1. Received from openstreetmap "Valencia" but "València"  in geojson
Tested with https://nominatim.openstreetmap.org/reverse?format=json&lat=39.4271294470365&lon=-0.8663281562502531&zoom=8&addressdetails=1&accept-language=es
2. Received from openstreetmap "Gerona" but "Girona" in geojson
Tested with https://nominatim.openstreetmap.org/reverse?format=json&lat=42.124818507961336&lon=2.729617274154627&zoom=8&addressdetails=1&accept-language=es
2. Received from openstreetmap "Alicante" but "Alacant" in geojson
Tested with https://nominatim.openstreetmap.org/reverse?format=json&lat=38.52134644552799&lon=-0.37103329879899116&zoom=8&addressdetails=1&accept-language=es
2. Received from openstreetmap "Región de Murci" but "Murcia" in geojson
Tested with https://nominatim.openstreetmap.org/reverse?format=json&lat=37.82459302432988&lon=-1.3477247855292498&zoom=8&addressdetails=1&accept-language=es
2. Received from openstreetmap "Lérida" but "Lleida" in geojson
Tested with https://nominatim.openstreetmap.org/reverse?format=json&lat=42.06838324616863&lon=1.1442427212390878&zoom=8&addressdetails=1&accept-language=es

2022-03-18 11:24 UTC, Rukant commented
I've changed it to polygon in type because probably OpenStreetMap will have a lot of problems with that geojson file. I guess creating the areas with OpenStreetMap have some advantages, so I can try to change to do the changes to the geojson file in the future. Apart from the discrepancy in regional languages and spanish, some regions don't have a state_district field when it's the same as the state one. Let me know if that is a problem and, in that case, if there is a way we can bypass it.

2022-03-18 16:19 UTC, BilelJegham approved these changes

2022-03-18 16:22 UTC, BilelJegham commented
Ok, 
OpenStreetMap is more precise than polygon for borders. But polygon works fine.

Thx for your contribution. Congrats for your 1st pull request :confetti_ball:

2022-03-18 16:22 UTC, merged